### ISSUE TITLE
New function req: Add ISPF line commads 

### ISSUE THREAD

**Issue by zszabo14** [wizardofzos/zigi#227]
Add ISPF line commands, so if users are opening the PDS included in the repo from ISFP they can use line commands like add, commit, etc. (like in DBB GitISPFClient)

**Comment by lbdyck** [comment]
Can you explain how this would be used and how it would be an improvement over just calling zigi with the name of the repository to gain access to all the capabilities of zigi.

For example, with zigi, you can issue the command **TSO %ZIGI repo-name** and it will start in that repository. When the repository opens, all of the datasets are checked for updates and any updates are copied to the OMVS repository file system so that Git is aware of them. From that point, you have all the capabilities of zigi to add, commit, push, etc.

Thanks for any clarification you can provide.

**Comment by zszabo14** [comment]
It's OK

**Comment by lbdyck** [comment]
Can you elaborate on your "It's OK" comment - I'm not sure how to understand it.

Thank you

**Comment by lbdyck** [comment]
Also - you commented on another issue you can't install dev releases - version 2.7 is now GA so you should be able to get that release to verify your issues have been resolved.

**Comment by lbdyck** [comment]
[zgadd.zip](https://github.com/wizardofzos/zigi/files/4403810/zgadd.zip)

Updated and cleaner.

**Comment by zszabo14** [comment]
Thank You

**Comment by lbdyck** [comment]
OK - you twisted my arm (sort of) - try this and let me know what you think.
[zg.zip](https://github.com/wizardofzos/zigi/files/4409348/zg.zip)

Notes:  1. there is customization required to work - find *custom* 
             2. couldn't do the cherry on the cake 
             3. The command is ZG (or whatever you want to name it) and is used from the enhanced ispf member list.

comments/suggestions/etc are welcome and appreciated - this is definitely a work-in-progress and can easily be changed prior to release (even after release).

**Comment by lbdyck** [comment]
Here is another update on the zg command - several improvements. Note that it still requires minimal customization (find * custom* ) 
[zg.zip](https://github.com/wizardofzos/zigi/files/4422592/zg.zip)

Please let us know what you think. How adequate is this?

Note one update is that after a pds is processed once the info is 'remembered' in the ispf profile so the next time the user works with a member in the same pds they will not be prompted for a repository name. This does assume the same pds is not included in multiple repositories.

**Comment by zszabo14** [comment]
Thank You! I'm bit busy now with other issues, but I will test as soon as possible.
