### ISSUE TITLE
Error message IKJ79320I

### ISSUE THREAD

**Issue by markons** [wizardofzos/zigi#275]
At leaving the zigi ISPF main screen, following message appears:

 IKJ79320I Unable to free previously allocated data sets.  Enter ? for more information.+                                                                       
 IKJ56247I FILE SYS00122 NOT UNALLOCATED, IS NOT ALLOCATED                      
 ***  

Zigi V2R0 is installed under z/OS 02.04.00.

**Comment by lbdyck** [comment]
Can you please try this updated branch - git@github.com:lbdyck/zigi.git

You'll need to specify the specific branch during the clone process which is v2rx-pns and let us know if the problem still exists. I've not been able to recreate. If the problem still exists please provide the steps to recreate.

btw. this updated branch has many enhancements and now uses an action bar for menus instead of the intrusive menus in 2.0.

**Comment by markons** [comment]
Hello,

thanks, it seems it has solved the problem.

A GIT beginners question: while trying the functionality RM , I've deleted
the working copy of my z/OS PDS. I can still see the last version in GIT
under USS.
How can I pls. restore my working copy by means of ZIGI?

Regards,
Gabor


Am Mi., 19. Feb. 2020 um 17:18 Uhr schrieb Lionel B. Dyck <
notifications@github.com>:

**Comment by wizardofzos** [comment]
Refresh. The refresh option should repopulate the pds

**Comment by markons** [comment]
Thanks for the quick response!
And no, I've tried this already:

[image: image.png]

[image: image.png]
Regards
Gabor

Am Do., 20. Feb. 2020 um 12:18 Uhr schrieb wizardofzos <
notifications@github.com>:

> Refresh. The refresh option should repopulate the pds
>
> Sent from my wireless iPhone
>

**Comment by lbdyck** [comment]
While in the Current Repository display the REFRESH command will effectively recreate ALL of the z/OS datasets from the OMVS copies.  The OMVS directory that is mapped to a PDS must reside in the repository OMVS filesystem root.

Perhaps had you done a commit prior to the RM?  If so then a ROLLBACK could be used to recover.
